### ISSUE TITLE
Not all device functionality exposed to Client

### ISSUE THREAD

**Issue by jrandombob** [intiface/intiface-central#100]
Just got a Lovense Max 2.

Intiface-Central shows both the vibration and air pump functionality but doesn't appear to be passing the air pump to buttplug clients.

This is the Device List I'm getting from Intiface;
```
[
	{
		"DeviceList": {
			"Id": 2,
			"Devices": [
				{
					"DeviceIndex": 1,
					"DeviceName": "Lovense Max",
					"DeviceMessages": {
						"VibrateCmd": {
							"FeatureCount": 1,
							"StepCount": [
								20
							]
						},
						"BatteryLevelCmd": {},
						"StopDeviceCmd": {}
					}
				}
			]
		}
	}
]
```

But both functions are shown in Intiface-Central.
![image](https://github.com/intiface/intiface-central/assets/10472113/a09edd48-b5c1-4200-82d6-0ec71d0d9cda)

Happy to provide any logs and such if needed.

Normally I'd jump in and do a PR but Rust isn't my jam :(

**Comment by qdot** [comment]
What client library are you using? That looks like an older version of the protocol (probably v2), which didn't have support for constriction.

**Comment by jrandombob** [comment]
Ah, OK, that could explain it, I'm using ManagedButtplugIo, I've had issues getting the other C# libs to play nice (I swear Visual Studio cross-compatibility is just getting worse these days).

**Comment by qdot** [comment]
I'd recommend trying https://github.com/buttplugio/buttplug-csharp again. We've moved back to having a pure C# implementation (versus the weird Rust FFI thing we were doing), and it's up to date.

**Comment by jrandombob** [comment]
I'd initially tried that but was having some weird errors out of NuGet, I've now been able to get it installed and behaving.

Bit of gymnastics required to figure out how to talk to it but got there in the end.
