### ISSUE TITLE
Stroking at level 0 Solace

### ISSUE THREAD

**Issue by RandomInternetPreson** [intiface/intiface-central#117]
I have a solace and can connect to Intiface just fine, but the scale of 0-1 still has the thing stroking at 0 Stroker Oscillation Speed.  Is there a way to prevent this from happening?  I can press the power button and it stops stroking and doesn't turn the machine off, so when I readjust the slider it starts back up again.

Additionally, I can send Intiface commands like duration and intensity and those are working, but I don't want it to keep stroking at this 0 oscillation speed between commands.  It will keep stroking at this minimum speed until I press the power button.

**Comment by nputman** [comment]
I can confirm the same behavior.

**Comment by qdot** [comment]
Yeah, we're trying to figure this out now. There's something up with different firmware versions of the Solace.

**Comment by RandomInternetPreson** [comment]
> Yeah, we're trying to figure this out now. There's something up with different firmware versions of the Solace.

Thank you for looking into this, I can test any beta versions if needed since it seems to be affecting devices with certain firmware.

**Comment by dravpin** [comment]
> Yeah, we're trying to figure this out now. There's something up with different firmware versions of the Solace.

Any update? or eta?

**Comment by dravpin** [comment]
> Yeah, we're trying to figure this out now. There's something up with different firmware versions of the Solace.

anything on this? any luck?

**Comment by dravpin** [comment]
> Yeah, we're trying to figure this out now. There's something up with different firmware versions of the Solace.

......

**Comment by dravpin** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by qdot** [comment]
Work continues. No update available on ETA.

**Comment by dravpin** [comment]
> Work continues. No update available on ETA.

I see

**Comment by qdot** [comment]
This should be fixed in Intiface Central v2.5.7, which was just released. Closing.
