### ISSUE TITLE
Feature: "Sync all together"

### ISSUE THREAD

**Issue by isaacclarke80** [intiface/intiface-central#118]
Would it be possible for there to be a "Sync all together" option for devices - for when certain apps are connected to Initface (looking at Faptap), but only seem to send commands to a single device - but the user wants all devices to be activated.

**Comment by qdot** [comment]
It's possible, but it's also a decent amount of work on our end. What's your use case here?

**Comment by isaacclarke80** [comment]
Mainly so I can have multiple toys connected to Faptap via IC... Not much of an Intiface use case I must admit :/

**Comment by qdot** [comment]
Yeah this is a "ask the application implementor" situation.
