### ISSUE TITLE
Axis Limits for serial TCode v0.3 devices

### ISSUE THREAD

**Issue by Ali-Saket** [intiface/intiface-central#129]
For serial TCode v0.3 devices (tested on OSR2+, Intiface Central 2.6.0 and EDI from 05/2024) seemingly the axis limit slider only constrains movement for the oscillation function of Intiface Central itself but not for signals routed through. Expected behavior is scaling the incoming signal to the limit slider. 

Searching on the [forum](https://discuss.buttplug.io/t/using-osr2-sr6-with-current-intiface-central-version-2-3-0/69/4), it seems others have the same problem.

**Comment by qdot** [comment]
This is a problem in general with linear movement restriction, it's not working for things like the Keon either. Will hopefully fix it in the next version.

**Comment by qdot** [comment]
Filed here: https://github.com/buttplugio/buttplug/issues/639

**Comment by Ali-Saket** [comment]
Ah, my keywords didn't match that. Will close it as duplicate. Thanks for all you do @qdot.
