### ISSUE TITLE
Install using Winget

### ISSUE THREAD

**Issue by claymorwan** [intiface/intiface-central#131]
It would be nice if we could install and update through Winget

**Comment by legowerewolf** [comment]
I'll look at doing this. I already maintain another package on the community repository; this won't be hard.

**Comment by legowerewolf** [comment]
https://github.com/microsoft/winget-pkgs/pull/171285

**Comment by legowerewolf** [comment]
I very much encourage @qdot to have a look over the manifest and let me know if there's anything I should update before I unmark it as a draft. If I hear nothing, I'll put it through in a couple days anyway because the metadata can be updated later.

**Comment by qdot** [comment]
Manifest looks fine, but it's going to be obsolete as 2.6.2 will hopefully be out later today, and after the issues with 2.6.1, you'll want to give that a couple of days to bake and make sure it's ok (there's a *lot* of opaque changes in our lower libraries that may have bugs). I'd wait to submit this until that's done.

**Comment by legowerewolf** [comment]
Sounds good. I'll cancel this one, then.

**Comment by legowerewolf** [comment]
Does Intiface Central need one of the Visual C/C++ redistributables?

https://github.com/microsoft/winget-pkgs/pull/171326#issuecomment-2327143175

**Comment by qdot** [comment]
Yup, it's a flutter requirement, and our rust libraries may need it too: https://docs.flutter.dev/platform-integration/windows/building#building-your-own-zip-file-for-windows

**Comment by legowerewolf** [comment]
Alright, I'll add that to the manifest in a bit.

**Comment by stephengillie** [comment]
Howdy - I work in this package manager's repo. I saw the link and wanted to give feedback about this package in particular. 

Our repo policies - [Policy 2.7](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#27-adult-content) in particular - will need both the application and the manifest to be relatively sterile and innocuous. The application's purpose and operation aren't much different from some of the RGB light controlling software currently in the repo, but the language and links describing its specific intent aren't a good fit for our repo and package manager. Some of the words in the `Description` and `ShortDescription`, and links in the application's About tab, are preventing the manifest from being merged. Ideally, it would be something that a suburban mother could download and review without being offended.

**Comment by legowerewolf** [comment]
Hm. Missed that. Would updating the ShortDescription and Tags to this be sufficient on the manifest side?

```yaml
ShortDescription: Software for managing, controlling, and customizing atypical haptic feedback devices.
Moniker: Intiface Central
Tags:
- intiface
```

As for the About tab... There's only so much to do. The library is called what it's called. If that's still a deal-breaker, then I think the only solution would be to [spin up our own private WinGet repo](https://github.com/microsoft/winget-pkgs/blob/master/doc/private/README.md) and host it there. Which sounds way more complicated than we probably want to do.

**Comment by qdot** [comment]
Ok, so, I'll hop in here since this is my software *and* my branding.

First off, @stephengillie, thanks for getting in touch! I'm happy to work with you on this, as this is a problem we face in a *lot* of different services. My projects kind of act as a somewhat-accidental boundaries test for generic software services, but it's something I'm happy to work out.

I think the terminology `various haptics devices` should be fine, as that is fully descriptive of what we handle, just in a slightly more abstracted sense. The Intiface branding was built *specifically* to handle situations like this, as we also cannot use the library name in places like the Google or Apple app stores.

In terms of the About tab, if you can give me more of a context about which links are offensive there, it's something we can talk about. That said, this app is already on the Microsoft/Google/Apple/soon-to-be Steam stores with no reported issues and a substantial number of downloads. Whether the restrictions for winget are comparable to those situations, I don't know, but we can see what can be done.

**Comment by stephengillie** [comment]
Hi @legowerewolf and @qdot,

Thanks each for responding, and for your patience. This topic is a little outside of my normal work.

> Hm. Missed that. Would updating the ShortDescription and Tags to this be sufficient on the manifest side?

> I think the terminology `various haptics devices` should be fine, as that is fully descriptive of what we handle, just in a slightly more abstracted sense. 

I agree completely. Please do make this change. I had suggested using the library's initialis in https://github.com/microsoft/winget-pkgs/pull/171285, but your suggestions are better.

---

> [spin up our own private WinGet repo](https://github.com/microsoft/winget-pkgs/blob/master/doc/private/README.md) and host it there.

I've made the joke to a colleague that this library represents an instance where an adult-themed package manager could be useful. 

---

> In terms of the About tab, if you can give me more of a context about which links are offensive there, it's something we can talk about. 

Please consider the text of [Policy 2.7](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#27-adult-content):

> The Product must not contain or display content that a reasonable person would consider pornographic or sexually explicit.

The name of the library itself might be considered explicit to some, and it's displayed on the About page. If the link text were changed, without changing the link destination, then the application would no longer be displaying this content and should meet Policy 2.7's requirement. At that point, I believe it could be merged.

**Comment by qdot** [comment]
> The name of the library itself might be considered explicit to some, and it's displayed on the About page. If the link text were changed, without changing the link destination, then the application would no longer be displaying this content and should meet Policy 2.7's requirement. At that point, I believe it could be merged.

Well, thanks for the considerations and discussion, but we're probably just gonna have to call this a no-go. I do get the requirement, but if you're going to be checking content that far back in UI, and we have dynamically updating news that may contain offensive words, this isn't gonna work. I'm certainly not changing product brand around one user's request for a package manager that we've had no other requests for.

@legowerewolf You're on your own. If you want your own repo, fine, but this looks pretty intractable for the public repo, so I'm gonna close out.

**Comment by qdot** [comment]
> I've made the joke to a colleague that this library represents an instance where an adult-themed package manager could be useful.

Also if anyone actually *does* do this let me know. Mainly because I'm curious who else other than me would show up on it. 😆

**Comment by legowerewolf** [comment]
Yeah, alright, I'll take down the merge request. It'd be _really nice_ if "setting up your own WinGet repo" was as simple as "here's a path structure on my web server that matches a spec" (or it technically is, making that spec public/easy to access).
