### ISSUE TITLE
Is the Constrict exposed to clients or not?

### ISSUE THREAD

**Issue by ABoredBunny** [intiface/intiface-central#148]
I recently got myself a Moonhorn. I noticed that the suction wasn't being controlled by the input.

So I started working on a javascript app that sits in the middle between the intiface central server and the client. In an effort to make these devices with pre defined patterns more interesting. It would pick patterns by analysing the input vibration on how much they change and there average intensity.

I was working on the Client emulation. I wiresharked between scriptplayer and intiface.
And noticed that the intiface server send this to the client:

[{"DeviceList":{"Id":2,"Devices":[{"DeviceIndex":0,"DeviceName":"JoyHub Moon Horn","DeviceMessages":{"VibrateCmd":{"FeatureCount":1,"StepCount":[255]},"StopDeviceCmd":{}}}]}}]

The server did not report the suction as a feature. I would need it to be exposed for my porpose.
Unless MessageVersion 3 exposes it. In which case sending me the client server log for a version 3 session would also help.

**Comment by qdot** [comment]
Yup, you're looking at a spec v2 stream, before we had ScalarCmd and types. ScriptPlayer is using a *very* old version of buttplug C# I'm guessing. That info should definitely come over with a v3 stream.
 
> So I started working on a javascript app that sits in the middle between the intiface central server and the client. 

Hah I'm building something quite similar, as this ability to filter was always supposed to be a part of the system (the "filter" layer) but I've never had time to build it. Feel free to hmu on discord or something if you want to talk more about this.

**Comment by ABoredBunny** [comment]
> Yup, you're looking at a spec v2 stream, before we had ScalarCmd and types. ScriptPlayer is using a _very_ old version of buttplug C# I'm guessing. That info should definitely come over with a v3 stream.
> 
> > So I started working on a javascript app that sits in the middle between the intiface central server and the client.
> 
> Hah I'm building something quite similar, as this ability to manipulate and reform incoming messages was always supposed to be a part of the system (the "filter" layer) but I've never had time to build it. Feel free to hmu on discord or something if you want to talk more about this.

I'm not much of a discord person. It's not really that special. It emulates a server. Looks for the VibrateCmd message. It creates two scores. An average running intensity and a Variety score. Then there's supposed to be a script with branches and a pretend client.

I did the Server emulation, and the variety and intensity score. Now I am working on the script stuff. 

I just need a Capture/Description of V3 Traffic or something that I can run that uses V3 to capture traffic myself.

Thanks for your time.

**Comment by ABoredBunny** [comment]
@qdot **Alright**. So I am mostly done. But there is an **issue with how Intiface handles Inputs.**


### When I sent a ScalarCmd it sets it for things that aren't supposed to be changed.

_When you change the constrict value on a moonhorn it resets the pattern_, even if that value is the exact same **pattern it is currently on.**

But if that was the only issue, I could just send a ScalarCmd that only changes the vibration(Vibration is passedthrough).

But even if I only change vibration it retriggers  the Constrict Pattern.

The whole way this is supposed to work is that there's logic that knows at what stage of the constrict the Moonhorn is(I painfully frame counted the patterns) and it triggers switch conditions based on Intensity and Variety.

But the constrict feature doesn't move because the Vibrations are being updated in real time.

### So my issue is: If one value is changed with a Scalar command it updates other Scalar commands.
Although I know this is a unique problem.

**The Effect of this is**, I can see the number change on the Moonhorn, but the constrict is in a _deadlock_ because it is constantly _retriggered_ by the _Vibration_ value changing. I wasn't sure if it is only If I update both like

### "[{"ScalarCmd": {"Id": 4,"DeviceIndex": 0,"Scalars": [{"Index": 0,"Scalar": 1.0,"ActuatorType": "Vibrate"},{"Index": 1,"Scalar": 0.9,"ActuatorType": "Constrict"}]}}]"

**But it also happens if I only update Vibrations.**
### "[{"ScalarCmd": {"Id": 5,"DeviceIndex": 0,"Scalars": [{"Index": 0,"Scalar": 0,"ActuatorType": "Vibrate"}]}}]"

**would stop the Constrict Pattern.**

(I don't know if you would fix it by only updating if a pattern changes, or if it is send.
[{"ScalarCmd": {"Id": 4,"DeviceIndex": 0,"Scalars": [{"Index": 0,"Scalar": 1.0,"ActuatorType": "Vibrate"},{"Index": 1,"Scalar": 0.9,"ActuatorType": "Constrict"}]}}]
If after this;
I send this:
[{"ScalarCmd": {"Id": 5,"DeviceIndex": 0,"Scalars": [{"Index": 0,"Scalar": 0,"ActuatorType": "Vibrate"},{"Index": 1,"Scalar": 0.9,"ActuatorType": "Constrict"}]}}]
I would appreciate if it didn't retrigger Constrict because my current code is build around this, of course if you updated it so it would still retrigger it, I would just change my code so it would only send Vibrate.
Or is there some way to do it already I don't know about.)
