### ISSUE TITLE
Add Solace Pro support?

### ISSUE THREAD

**Issue by TheEternalDarkness** [intiface/intiface-central#150]
Currently the intiface central tooling does not look like it can detect/integrate with the Solace Pro, which seems to have positional stroke controls rather than oscillating ones like the prior Solace.

Is there any way / plans to get this integrated?  bp.io support on iostindex says bp.io supports it.

**Comment by qdot** [comment]
The Solace Pro *does* have oscillating controls currently, and we're working on linear controls. If you're curious about that work, the last two VODs on my twitch are me reversing that on stream: https://twitch.tv/buttplugio

At the current rate I'm hoping we'll have some sort of support in the next couple of weeks, but right now the implementation looks *weird*, so I'm not sure what the quality will be yet.

**Comment by qdot** [comment]
Done in v2.6.4
