### ISSUE TITLE
Moonhorn, vibration updates interrupt Suction

### ISSUE THREAD

**Issue by ABoredBunny** [intiface/intiface-central#152]
#148 I finished my Pattern Picker. However there is a problem, every time vibration is updated the constrict pattern is interrupted. I Intially thought it is that Intiface resends both.

But it might also be related to how Intiface sends Bluetooth messages.
And that the message it sends when vibration is updated updates both values. 

I tested and it didn't happen in Joyhub, and it also does it when changing it on the interface(not just when sending a message). 

In the bluetooth logs in wireshark of Joyhub Vibration is:
 02 02 00 0e 00 0a 00 04 00 52 0e 00 a0 03 (ff) 00 00 00 aa
(Vibration value in HEX)

The Constrict pattern is:
02 02 00 0d 00 09 00 04 00 52 0e 00 a0 0d 00 00 (04) ff
(Pattern value in HEX)

But I don't know if that is relevant to how intiface sends it.

**Comment by qdot** [comment]
This is really a bug for https://github.com/buttplugio/buttplug, as Intiface is just the frontend and the protocol implementation is there. That said, pinging @blackspherefollower to take a look at this.

**Comment by ABoredBunny** [comment]
@qdot How do I build Intiface with a local version of buttplug? The issue was fixed. Now I need to compile a version with the fix before I can use/test/publish my "app"

**Comment by qdot** [comment]
You'll have to build local versions of buttplug, intiface-engine, and intiface-central, all aligned to use the same buttplug/intiface-engine dependencies. Just check the 3 repos out next to each other and edit the Cargo.toml files in each, I leave the dev paths for that setup commented out in those.
