### ISSUE TITLE
Add kiiroo pulse solo support

### ISSUE THREAD

**Issue by suser13** [intiface/intiface-central#155]
Initface central does not detect the Kiiroo pulse solo vibrator.

Where should I start looking to add support for that?, I assume there is a separate repo for buttplug,  any pointers will be greatly appreciated.

Also, is there a way to purchase that device and send it to the dev team?

**Comment by suser13** [comment]
Cant reproduce on desktop. Closing.

**Comment by qdot** [comment]
So was it not working on mobile but is working on desktop? 'cause yeah we do support it.
