### ISSUE TITLE
Device-config is only read from disk if a User-config exists

### ISSUE THREAD

**Issue by blackspherefollower** [intiface/intiface-central#157]
The built-in (and potentially out-of-date) device config is used by Intiface unless a device has already been added, causing the creation of a user-config. See https://github.com/intiface/intiface-central/blob/main/lib/bloc/device_configuration/user_device_configuration_cubit.dart#L31-L33 for the offending block.

The removal of this block (or adding a user config) appears to cause logging from the rust layers to be suppressed: we stop seeing the list of loaded protocols that don't have implementations or the info messages regarding whether the config loaded was internal or "custom". This suggests that the initialization order might not be correct.

**Comment by qdot** [comment]
Fixed in v2.6.5
