### ISSUE TITLE
 Bluetooth Le not found even tho I have the USB plugged in

### ISSUE THREAD

**Issue by claymorwan** [intiface/intiface-central#162]
I have the lovense USB plugged in to connect to my hush 2, but for some reason I get this warning
![image](https://github.com/user-attachments/assets/8f832366-24d7-4fb9-a336-e3d1510b2185)
Plus, when scanning, It doesn't find my device.

OS: Arch linux 6.12.4-arch1-1 (64-bit)
I have both bluez and bluez-utils installed, and my bluetooth service enabled.

**Comment by blackspherefollower** [comment]
@claymorwan The Lovense USB dongle isn't a generic Bluetooth dongle. You'll need to enable the Lovense HID dongle device manager.

This also isn't the best place for asking support question: there's a support forum on the buttplug.io discord that has a much faster response time.

**Comment by claymorwan** [comment]
> @claymorwan The Lovense USB dongle isn't a generic Bluetooth dongle. You'll need to enable the Lovense HID dongle device manager.
> 
> This also isn't the best place for asking support question: there's a support forum on the buttplug.io discord that has a much faster response time.

O that makes sense now,I thought this was related to the app so that's why I asked for help here. I'll go check about this HID thingy, thanks :3
