### ISSUE TITLE
Server should run StopAllDevices before exiting

### ISSUE THREAD

**Issue by Furimanejo** [intiface/intiface-central#30]
Steps to reproduce: 

1. Run intiface central
2. Start server
3. Scan for devices
4. Set a device to a non-zero value (tested with a lovense edge 2)
5. Stop server

Expected behaviour: the device stops instantly.
Current behaviour: the device delays a couple seconds before stopping.

6. Start the server again
7. Scan for devices

Expected behaviour: the device connects with the default value (zero) set.
Current behaviour: the device connects and is set to the value set before the server was closed (on step 4).

**Comment by qdot** [comment]
Tested with Lovense Edge 2, Lovense Hush, and OhMiBod Lumen. Cannot repro device value reset on reconnect after server stop/start.

Narrowing focus of bug to stopping devices before server stops.

**Comment by qdot** [comment]
Fixed in v2 via Buttplug v6.2.2
