### ISSUE TITLE
Server Address doesn't show the configured server port

### ISSUE THREAD

**Issue by Lordmau5** [intiface/intiface-central#38]
I've had to change the Server Port to something other than the default and noticed it's not showing the new port in the app, even when the server is running

![image](https://user-images.githubusercontent.com/1345036/206728694-023322de-7f84-432b-b759-47f27a62d26c.png)

**Comment by qdot** [comment]
FINALLY fixed in v2.4.1. I had just forgotten to sub in the variable in the string. Cannot believe I let this sit for 7 months.

**Comment by Lordmau5** [comment]
Better late than never 😄
