### ISSUE TITLE
Misleading website statement on open-source status 

### ISSUE THREAD

**Issue by LucyBun** [intiface/intiface-central#39]
Hey there,

Totally understand the need to at this time restrict the access to the source code for Intiface Central until an official version is posted on all planned app stores, though this (until then) makes the statement on the website [here](https://intiface.com/central/) misleading: "Intiface® Central is an open-source, cross-platform application...". 

Recommend updating that to make clear that it is currently closed source but planning to be open source. Advertising something as open-source before it is creates an expectation that it has been subject to community review before it has been. It surprised me, and sent alarm bells ringing, and I'd hate for anyone introduced to such an excellent tool to get the wrong idea.

**Comment by qdot** [comment]
Fixed by just actually releasing the source code. :3
