### ISSUE TITLE
Linux version 2.2.2 after installation still reports as version 2.2.0

### ISSUE THREAD

**Issue by johnlong21** [intiface/intiface-central#54]
after downloading the new release of Intiface Central v2.2.2 for Linux after running it opens up and still reports there is a new version (aka 2.2.2), and going to the settings it still reports as v2.2.0 .

noticing this i hit the "reset application configuration" think the older configuration could be causing this but after doing that even though everything is now back to default the version is still wrong.

i think one possibility that could of happen is that the version of the release is the older 2.2.0 version as looking at the folder name in the zip it still says "intiface_central_v2.2_linux_x64".
![Screenshot of linux release v2 2 2](https://user-images.githubusercontent.com/66089088/213304983-125e12c7-66ae-4a93-bcab-e65d2663e757.png)

**Comment by qdot** [comment]
And this is why I need CI. Pretty sure I built the wrong version and released it as 2.2.2 >.>

I'll try to get this fixed in the next day or two.

**Comment by qdot** [comment]
This got fixed with v2.3.0
