### ISSUE TITLE
Android: arm32 (armeabi_v7a) fails

### ISSUE THREAD

**Issue by kyanha** [intiface/intiface-central#59]
Per blackspherefollower on Discord:

On Android:

The intiface_central APK declares support for 32-bit ARM, but doesn't have the intiface rust parts for 32-bit ARM. This causes it to fail on my (purchased less than 1 year ago) Samsung A13 5G.

**Comment by kyanha** [comment]
If there is no forthcoming support for 32-bit ARM, please remove 32-bit ARM from the declared and packaged support, so that 32-bit platforms aren't offered Intiface via Google Play.

**Comment by qdot** [comment]
Fixed in Android v2.3.1
