### ISSUE TITLE
Trying to connect to game FarmD, server stops and error pops up

### ISSUE THREAD

**Issue by AxiomAtom** [intiface/intiface-central#65]
While the Intiface Central server is running I try to connect to it in the game FarmD but as soon as the server is found the Intiface Central server stops and sends out errors:
Websocket server accept error: Protocol(HandshakeIncomplete)
Process Error: ConnectorError("TransportSpecificError(TungsteniteError(Protocol(HandshakeIncomplete)))")

**Comment by kaciexx** [comment]
Change the port number

**Comment by qdot** [comment]
This is months old. Closing.

There's a chance this could've happened via issues with mixed content, but not sure.
