### ISSUE TITLE
U.F.O TW cannot rotate two at the same time

### ISSUE THREAD

**Issue by terakoya-san** [intiface/intiface-central#67]
U.F.O. TW cannot rotate the left and right motors at the same time. Is this a device specification? Or is this a glitch that will be corrected in the future?

**Comment by qdot** [comment]
@terakoya-san What happens specifically? If you make one rotate the other stops?

**Comment by terakoya-san** [comment]
yes, when rotate one, the other side will stop.

**Comment by qdot** [comment]
Fixed in v2.4
