### ISSUE TITLE
Need an easy way for users to export logs

### ISSUE THREAD

**Issue by blackspherefollower** [intiface/intiface-central#70]
Right now for desktop platforms, the logs can be found if you know where to look, but on mobile OSs those locations are not accessible.

It'd be really handy to have a "Send logs" button that would allow the log file to be sent to another application (likely discord)

For anyone looking for their logs:
* Windows: `C:\Users\<user>\AppData\Roaming\com.nonpolynomial\intiface_central\logs`
* macOS: `/Users/<username>/Library/Containers/com.nonpolynomial.intifacecentral/Data/Library/Application Support/com.nonpolynomial.intifacecentral/logs`

**Comment by qdot** [comment]
Done in v2.4.4 via the sentry sending. Still be nice to have a button somewhere that just opens the log directory in their file explorer, but we'll file that as a followup if we end up wanting that too.
