### ISSUE TITLE
Building on linux requires root privileges

### ISSUE THREAD

**Issue by bigryanfan** [intiface/intiface-central#73]
When building git HEAD on Arch linux as a normal user I get this:

```
$ flutter build linux

[...]

CMake Error at cmake_install.cmake:66 (file):
  file INSTALL cannot copy file
  "<SRC_PATH>/intiface-central/build/linux/x64/release/intermediates_do_not_run/intiface_central"
  to "/usr/local/intiface_central": Permission denied.


Building Linux application...                                           
Build process failed
```

It shouldn't require root privileges to just build (not install) this, should it?

**Comment by qdot** [comment]
All of our builds happen on Ubuntu, and I've never seen this issue. We can really only support what we CI for, so I'm just gonna have to close this as WONTFIX for now 'cause there's no way I can support building every distro by myself.
