### ISSUE TITLE
Listening address is causing confusion 

### ISSUE THREAD

**Issue by blackspherefollower** [intiface/intiface-central#78]
I've helped 2 users recently who have entered `localhost:12345` into clients that interpret the address as a URI and default to http.

I partly think this might be made better in buttplug-c# but I'm also wondering if adding the protocol specifier to the listening address shown in Intiface (i.e `ws://localhost:12345`) might be clearer in some cases?

**Comment by qdot** [comment]
Done, will be in v2.4.1
