### ISSUE TITLE
Connecting to wss: protocol on Android/IOS it disconnects the server!!!!!

### ISSUE THREAD

**Issue by danielalmering** [intiface/intiface-central#79]
Error log:

Process Error: ConnectorError("TransportSpecificError(TungsteniteError(Protocol(HttparseError(Token)))

Tested on both Android & IOS both gave same error!!

btw on ws:// works fine but needed a secure connection to webpage

**Comment by qdot** [comment]
We don't support wss:// to the system currently, because managing self signed certs was a nightmare. We'll probably end up providing a proxy system soon.

Closing as won't fix.
