### ISSUE TITLE
Linux builds should vendor OpenSSL for compatibility

### ISSUE THREAD

**Issue by qdot** [intiface/intiface-central#83]
We never know what distro we're running on, and OpenSSL seems to be the culprit in a lot of compat issues (though libudev/dbus may also cause problems here). Vendor OpenSSL builds into the rust library.

**Comment by selfisekai** [comment]
can this be a cargo feature? when building within a distro, compatibility is our job here

**Comment by LeGrosFromage** [comment]
Version 2.4.3 works correctly.  When I posted the original issue we were still on 2.4.2.  Not sure what changed, but it is working now on 2.4.3.
