### ISSUE TITLE
v2.4.3 Start Scanning request failed: Java exception was thrown

### ISSUE THREAD

**Issue by GenesisHypno** [intiface/intiface-central#84]
![1](https://github.com/intiface/intiface-central/assets/134281988/c3f3c533-2c9c-443e-800f-6d1816a3b868)

![2](https://github.com/intiface/intiface-central/assets/134281988/4f395272-24b3-4afd-9084-5eeaeaaf6de9)

It's sadly still not fixed in v2.4.3. Can't use Intiface-Central with any device.

I have a Samsung Galaxy Note 8. Hope that helps.

Regards GenesisHypno

**FIXED WITH NEWEST UPDATE!!!**

**Comment by qdot** [comment]
Oh, it's a Samsung. We're seeing this problem almost purely on samsung phones, which is making me think there's some sort of issue with their android distro/bluetooth stack. Not quite sure how we're going to fix this.

**Comment by fuyushi** [comment]
Same issue with Oneplus 7 Pro (OxygenOs 12.1 Android 12) 
![Screenshot_2024-03-24-20-02-45-12_54e1856646d1776c03c13fa9d22d49e9](https://github.com/intiface/intiface-central/assets/23568789/50a278ab-0a32-4e90-8732-52ff699e2823)

**Comment by qdot** [comment]
Yeah, we're still getting a ton of these, and I can't for the life of me manage to repro it. If anyone submitting logs here has the tools/experience to run `adb logcat` against their phone while this is happening, please let me know.

**Comment by fuyushi** [comment]
I have a logcat, but I dont know if theres too sensitive information in these to upload here

**Comment by qdot** [comment]
@fuyushi Can you email it to me? kyle at nonpolynomial dot com

**Comment by qdot** [comment]
This is now filed over at https://github.com/deviceplug/btleplug/issues/375, I'll update here once I have an idea of what to do about it.

**Comment by tigerwee** [comment]
Privacy code 
Stop using my camera

**Comment by qdot** [comment]
Pretty sure this is #136. Gonna mark this as a dupe since we're tracking on top of sentry in #136

**Comment by qdot** [comment]
Still not fixed yet, but now tracking at #136
