### ISSUE TITLE
macOS CI Builds not settings executable mode correctly

### ISSUE THREAD

**Issue by qdot** [intiface/intiface-central#85]
When the CI builds a macOS app, the executable permissions are getting wiped at some point, which means the app won't run

**Comment by LeGrosFromage** [comment]
To answer the question from #81 this is actually a M1 Mac.  However, similar to the Linux issue I reported, 2.4.3 cleared up the problem and is working for me.

Let me know if you need any debug info or such for any reason... willing to help with builds/test on Mac and Linux.

**Comment by qdot** [comment]
Yeah that's me being sneaky. I uploaded a new macOS 2.4.3 with fixed permissions. :3 

Still need to fix this in CI though, as well as fixing signing, so gonna leave this open.

**Comment by qdot** [comment]
Seems to be fixed in CI? I'm guessing what happens what I repacked this on windows or something and lost the permissions there.
