### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by Fabillotic** [intiface/intiface-central#88]
For all of the Arch Linux users I wrote and published an AUR package at [intiface-central-bin](https://aur.archlinux.org/packages/intiface-central-bin)
This package has a fix for issue #40 by including a simple run script and it also features a simple desktop entry file.
My intention is to continue maintaining it, although I'm happy to give the package over to someone more experienced / involved in the project.
I made this thread for discussing suggestions and issues with the package.
Hope it helps! :3

**Comment by qdot** [comment]
Thanks! I'll close this once I remember to get it added to our README/webpage.

BTW, next version should remove the openssl dependency which will make life easier on everyone.
