### ISSUE TITLE
./intiface_central: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./intiface_central)

### ISSUE THREAD

**Issue by thedevleon** [intiface/intiface-central#89]
I'm trying to run `intiface-central-v2.4.3-linux-x64` on Ubuntu 20.04.1 and getting the following error:

``` ./intiface_central: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./intiface_central) ```

It seems that my currently installed version of glibc is 2.31:

```
$ sudo apt install libc6
libc6 is already the newest version (2.31-0ubuntu9.9).
```
I guess this means I have to update to Ubuntu 22.04? Maybe this can be mentioned in the webpage, or the binary  could be compiled with an older GLIBC version so it's also compatible with Ubuntu 20.04?

**Comment by qdot** [comment]
Our CI is 22.04, so that's what we support for the moment. Build instructions are now in the README for other platforms.

**Comment by qdot** [comment]
@thedevleon As of 2.5, I'm now building for both 20.04 and 22.04. Check the github releases (I'll have it posted to the main intiface page soon)
