### ISSUE TITLE
Can't connect Svakom Sam Neo to Intiface, tried 3 diff BT adapters

### ISSUE THREAD

**Issue by GordonHollow** [intiface/intiface-central#90]
When i start searching it found device, connect and instantly disconnect, with this error in log

Device errored while trying to connect: Device type specific error: Btleplug error: Not connected

Latest Intiface 2.4.3, also try mobile app too with same result

It works fine on xtoys\app and site with BT adapters i have tho
![изображение](https://github.com/intiface/intiface-central/assets/23491996/2514b938-956a-44eb-80d2-8add1e8744ba)

**Comment by qdot** [comment]
This is waiting on a new release of Intiface Central. We've got the updates in our library, I've just been busy with other parts of the project so this has lagged a bit. Hoping for a release in the next week or so.

**Comment by qdot** [comment]
Should be fixed in >= v2.4.4

**Comment by GordonHollow** [comment]
> Should be fixed in >= v2.4.4

I tried 2.4.4 and 2.4.5
same problem
![изображение](https://github.com/intiface/intiface-central/assets/23491996/c1b8635c-4eda-48db-ae6c-f2f5333e4fc3)

**Comment by qdot** [comment]
Ok, in 2.4.5, can you start the server, try scanning, then go to the About/Help panel and hit "Send Logs to Developers"? Put a message about this relating to bug #90 so I'll know what to look for.

**Comment by GordonHollow** [comment]
> Ok, in 2.4.5, can you start the server, try scanning, then go to the About/Help panel and hit "Send Logs to Developers"? Put a message about this relating to bug #90 so I'll know what to look for.

done.

**Comment by qdot** [comment]
Might be fixed in v2.5.1/2.

**Comment by GordonHollow** [comment]
> Might be fixed in v2.5.1/2.

Still has same error as before, but now search takes way longer time, before it founds Sam and gets that error

**Comment by GordonHollow** [comment]
Still same error in 2.5.3 PC version, but latest mobile app now connected to Sam okay.
Sadly any sites i tried or MultiFunPlayer, that supposed to work with Intiface - don't connect with Intiface IP i have on phone
Mobile app instead just gives some Java error, when i try to connect to it from anything, and eventually crashes
